# generated by datamodel-codegen:
#   filename:  <dict>
#   timestamp: 2026-04-09T21:28:09+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class AIPlayerCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Player name', title='Name')
    player_type: Literal['ai'] = Field('ai', title='Player Type')
    ai_provider: str = Field(..., description='AI provider', title='Ai Provider')
    ai_model: str = Field(..., description='AI model', title='Ai Model')
    system_prompt: str | None = Field(
        None, description='System prompt', title='System Prompt'
    )
    temperature: float | None = Field(
        None,
        description='AI Temperature (controls randomness of AI responses)',
        title='Temperature',
    )


class AIPlayerResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int = Field(..., description='Player ID', title='Id')
    name: str = Field(..., description='Player name', title='Name')
    player_type: Literal['ai'] = Field('ai', title='Player Type')
    ai_provider: str = Field(..., description='AI provider', title='Ai Provider')
    ai_model: str = Field(..., description='AI model', title='Ai Model')
    system_prompt: str | None = Field(
        None, description='System prompt', title='System Prompt'
    )
    temperature: float | None = Field(
        None,
        description='AI Temperature (controls randomness of AI responses)',
        title='Temperature',
    )


class BodyUpdateDocumentV2CampaignsCampaignShortNameDocumentsPut(BaseModel):
    file: bytes = Field(..., title='File')


class CampaignResponse(BaseModel):
    id: int = Field(..., title='Id')
    full_name: str = Field(..., title='Full Name')
    short_name: str = Field(..., title='Short Name')
    roleplay_system: str = Field(..., title='Roleplay System')
    language: str = Field(..., title='Language')
    active_summary_file: str | None = Field(None, title='Active Summary File')
    session_log_file: str | None = Field(None, title='Session Log File')
    extensions: dict[str, Any] | None = Field(None, title='Extensions')


class CharacterType(Enum):
    pc = 'pc'
    party_member = 'party_member'
    npc = 'npc'
    passerby = 'passerby'
    monster = 'monster'


class CreateCampaignRequest(BaseModel):
    full_name: str = Field(..., title='Full Name')
    short_name: str = Field(..., title='Short Name')
    roleplay_system: str = Field(..., title='Roleplay System')
    language: str = Field(..., title='Language')
    active_summary_file: str | None = Field(None, title='Active Summary File')
    session_log_file: str | None = Field(None, title='Session Log File')
    extensions: dict[str, Any] | None = Field(None, title='Extensions')


class Disposition(Enum):
    friendly = 'friendly'
    neutral = 'neutral'
    hostile = 'hostile'
    unknown = 'unknown'


class ExpandQueryRequest(BaseModel):
    query: str = Field(..., title='Query')
    extra_context: str = Field(..., title='Extra Context')


class GameCharacterOnCampaignCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Character name', title='Name')
    category: CharacterType = Field(..., description='Character category')
    race: str | None = Field(None, description='Character race', title='Race')
    gender: str | None = Field(None, description='Character gender', title='Gender')
    age: int | None = Field(None, description='Character age', title='Age')
    sexual_orientation: str | None = Field(
        None, description='Character sexual orientation', title='Sexual Orientation'
    )
    alignment: str | None = Field(
        None, description='Character alignment', title='Alignment'
    )
    occupation: str | None = Field(
        None, description='Character occupation', title='Occupation'
    )
    is_active: bool | None = Field(
        True, description='Character is active', title='Is Active'
    )
    is_alive: bool | None = Field(
        True, description='Character is alive', title='Is Alive'
    )
    location: str | None = Field(
        None, description='Character location', title='Location'
    )
    faction: str | None = Field(None, description='Character faction', title='Faction')
    disposition: Disposition | None = Field(None, description='Character disposition')
    known_by_party: bool | None = Field(
        False, description='Character is known by party', title='Known By Party'
    )
    description: str | None = Field(
        None, description='Character description', title='Description'
    )
    data: Any = Field(None, description='Character data', title='Data')


class GameCharacterOnCampaignResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int = Field(..., description='Character ID', title='Id')
    name: str = Field(..., description='Character name', title='Name')
    category: CharacterType = Field(..., description='Character category')
    race: str | None = Field(None, description='Character race', title='Race')
    gender: str | None = Field(None, description='Character gender', title='Gender')
    age: int | None = Field(None, description='Character age', title='Age')
    sexual_orientation: str | None = Field(
        None, description='Character sexual orientation', title='Sexual Orientation'
    )
    alignment: str | None = Field(
        None, description='Character alignment', title='Alignment'
    )
    occupation: str | None = Field(
        None, description='Character occupation', title='Occupation'
    )
    is_active: bool | None = Field(
        True, description='Character is active', title='Is Active'
    )
    is_alive: bool | None = Field(
        True, description='Character is alive', title='Is Alive'
    )
    location: str | None = Field(
        None, description='Character location', title='Location'
    )
    faction: str | None = Field(None, description='Character faction', title='Faction')
    disposition: Disposition | None = Field(None, description='Character disposition')
    known_by_party: bool | None = Field(
        False, description='Character is known by party', title='Known By Party'
    )
    description: str | None = Field(
        None, description='Character description', title='Description'
    )
    data: Any = Field(None, description='Character data', title='Data')
    campaign_id: int = Field(..., description='Campaign ID', title='Campaign Id')


class GameCharacterOnCampaignUpdate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    category: CharacterType | None = Field(None, description='Character category')
    race: str | None = Field(None, description='Character race', title='Race')
    gender: str | None = Field(None, description='Character gender', title='Gender')
    age: int | None = Field(None, description='Character age', title='Age')
    sexual_orientation: str | None = Field(
        None, description='Character sexual orientation', title='Sexual Orientation'
    )
    alignment: str | None = Field(
        None, description='Character alignment', title='Alignment'
    )
    occupation: str | None = Field(
        None, description='Character occupation', title='Occupation'
    )
    is_active: bool | None = Field(
        None, description='Character is active', title='Is Active'
    )
    is_alive: bool | None = Field(
        None, description='Character is alive', title='Is Alive'
    )
    location: str | None = Field(
        None, description='Character location', title='Location'
    )
    faction: str | None = Field(None, description='Character faction', title='Faction')
    disposition: Disposition | None = Field(None, description='Character disposition')
    known_by_party: bool | None = Field(
        None, description='Character is known by party', title='Known By Party'
    )
    description: str | None = Field(
        None, description='Character description', title='Description'
    )
    data: Any = Field(None, description='Character data', title='Data')


class HumanPlayerCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Player name', title='Name')
    player_type: Literal['human'] = Field('human', title='Player Type')
    email: str = Field(..., description='Human player email', title='Email')
    age: int | None = Field(None, description='Human player age', title='Age')
    gender: str | None = Field(None, description='Human player gender', title='Gender')
    availability: str | None = Field(
        None, description='Human player availability', title='Availability'
    )
    notes: str | None = Field(None, description='Human player notes', title='Notes')


class HumanPlayerResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int = Field(..., description='Player ID', title='Id')
    name: str = Field(..., description='Player name', title='Name')
    player_type: Literal['human'] = Field('human', title='Player Type')
    email: str = Field(..., description='Human player email', title='Email')
    age: int | None = Field(None, description='Human player age', title='Age')
    gender: str | None = Field(None, description='Human player gender', title='Gender')
    availability: str | None = Field(
        None, description='Human player availability', title='Availability'
    )
    notes: str | None = Field(None, description='Human player notes', title='Notes')


class LLMMessage(BaseModel):
    role: str = Field(..., title='Role')
    content: str = Field(..., title='Content')


class QueryRequest(BaseModel):
    query: str = Field(..., title='Query')
    max_results: int | None = Field(5, title='Max Results')
    collection_name: str | None = Field(None, title='Collection Name')


class QueryResult(BaseModel):
    text: str = Field(..., title='Text')
    source_document: str = Field(..., title='Source Document')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')
