# generated by datamodel-codegen:
#   filename:  <dict>
#   timestamp: 2026-04-03T12:15:31+00:00

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class AIPlayerCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Player name', title='Name')
    player_type: Literal['ai'] = Field('ai', title='Player Type')
    ai_provider: str = Field(..., description='AI provider', title='Ai Provider')
    ai_model: str = Field(..., description='AI model', title='Ai Model')
    system_prompt: str | None = Field(
        None, description='System prompt', title='System Prompt'
    )
    temperature: float | None = Field(
        None,
        description='AI Temperature (controls randomness of AI responses)',
        title='Temperature',
    )


class AIPlayerResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int = Field(..., description='Player ID', title='Id')
    name: str = Field(..., description='Player name', title='Name')
    player_type: Literal['ai'] = Field('ai', title='Player Type')
    ai_provider: str = Field(..., description='AI provider', title='Ai Provider')
    ai_model: str = Field(..., description='AI model', title='Ai Model')
    system_prompt: str | None = Field(
        None, description='System prompt', title='System Prompt'
    )
    temperature: float | None = Field(
        None,
        description='AI Temperature (controls randomness of AI responses)',
        title='Temperature',
    )


class BodyUpdateDocumentV2CampaignsCampaignShortNameDocumentsPut(BaseModel):
    file: bytes = Field(..., title='File')


class CampaignResponse(BaseModel):
    id: int = Field(..., title='Id')
    full_name: str = Field(..., title='Full Name')
    short_name: str = Field(..., title='Short Name')
    roleplay_system: str = Field(..., title='Roleplay System')
    language: str = Field(..., title='Language')
    active_summary_file: str | None = Field(None, title='Active Summary File')
    session_log_file: str | None = Field(None, title='Session Log File')
    extensions: dict[str, Any] | None = Field(None, title='Extensions')


class CreateCampaignRequest(BaseModel):
    full_name: str = Field(..., title='Full Name')
    short_name: str = Field(..., title='Short Name')
    roleplay_system: str = Field(..., title='Roleplay System')
    language: str = Field(..., title='Language')
    active_summary_file: str | None = Field(None, title='Active Summary File')
    session_log_file: str | None = Field(None, title='Session Log File')
    extensions: dict[str, Any] | None = Field(None, title='Extensions')


class ExpandQueryRequest(BaseModel):
    query: str = Field(..., title='Query')
    extra_context: str = Field(..., title='Extra Context')


class HumanPlayerCreate(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str = Field(..., description='Player name', title='Name')
    player_type: Literal['human'] = Field('human', title='Player Type')
    email: str = Field(..., description='Human player email', title='Email')
    age: int | None = Field(None, description='Human player age', title='Age')
    gender: str | None = Field(None, description='Human player gender', title='Gender')
    availability: str | None = Field(
        None, description='Human player availability', title='Availability'
    )
    notes: str | None = Field(None, description='Human player notes', title='Notes')


class HumanPlayerResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int = Field(..., description='Player ID', title='Id')
    name: str = Field(..., description='Player name', title='Name')
    player_type: Literal['human'] = Field('human', title='Player Type')
    email: str = Field(..., description='Human player email', title='Email')
    age: int | None = Field(None, description='Human player age', title='Age')
    gender: str | None = Field(None, description='Human player gender', title='Gender')
    availability: str | None = Field(
        None, description='Human player availability', title='Availability'
    )
    notes: str | None = Field(None, description='Human player notes', title='Notes')


class LLMMessage(BaseModel):
    role: str = Field(..., title='Role')
    content: str = Field(..., title='Content')


class QueryRequest(BaseModel):
    query: str = Field(..., title='Query')
    max_results: int | None = Field(5, title='Max Results')
    collection_name: str | None = Field(None, title='Collection Name')


class QueryResult(BaseModel):
    text: str = Field(..., title='Text')
    source_document: str = Field(..., title='Source Document')


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(None, title='Detail')
